(function(){
  var html = "";
  html += '<xml id="toolbox" style="display: none">';
  html += '  <category id="category_initializes">';
  html += '    <block type="initializes_setup"></block>';
  html += '  </category>';
  html += '  <category id="category_inout">';
  html += '    <category id="category_digital">';
  html += '      <block type="inout_highlow"></block>';
  html += '      <block type="inout_digitalpin"></block>';
  html += '      <block type="inout_digital_write"></block>';
  html += '      <block type="inout_custom_digital_write">';
  html += '        <value name="PIN">';
  html += '          <block type="inout_digitalpin">';
  html += '            <field name="PIN">1</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="STAT">';
  html += '          <block type="inout_highlow">';
  html += '            <field name="BOOL">HIGH</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="inout_digital_read"></block>';
  html += '    </category>';
  html += '    <category id="category_analog">';
  html += '      <block type="inout_analog_write">';
  html += '        <value name="NUM">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">255</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="inout_analog_read"></block>';
  html += '    </category>';
  html += '    <category id="category_others">';
  html += '      <block type="pulsein"></block>';
  html += '      <block type="tone"></block>';
  html += '      <block type="custom_tone">';
  html += '        <value name="FREQ">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">255</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '    </category>';
  html += '  </category>';
  html += '  <category id="category_serial">';
  html += '    <block type="serial_available"></block>';
  html += '    <block type="serial_print">';
  html += '      <value name="CONTENT">';
  html += '        <block type="text">';
  html += '          <field name="TEXT"></field>';
  html += '        </block>';
  html += '      </value>';
  html += '    </block>';
  html += '    <block type="serial_println">';
  html += '      <value name="CONTENT">';
  html += '        <block type="text">';
  html += '          <field name="TEXT"></field>';
  html += '        </block>';
  html += '      </value>';
  html += '    </block>';
  html += '    <block type="serial_read"></block>';
  html += '    <block type="serial_byte_number"></block>';
  html += '  </category>';
  html += '  <category id="category_ethernet">';
  html += '    <category id="category_ethernet_init">';
  html += '      <block type="ethernet_begin_dhcp">';
  html += '        <value name="MAC_ADDRESS">';
  html += '          <block type="ethernet_mac_address"></block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="ethernet_localip"></block>';
  html += '    </category>';
  html += '    <category id="category_ethernet_client">';
  html += '      <block type="ethernet_connect">';
  html += '        <value name="SERVER">';
  html += '          <block type="text">';
  html += '            <field name="TEXT">www.google.com</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="ethernet_stop"></block>';
  html += '      <block type="ethernet_connected"></block>';
  html += '      <block type="ethernet_available"></block>';
  html += '      <block type="ethernet_print">';
  html += '        <value name="TEXT">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="ethernet_println">';
  html += '        <value name="TEXT">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="ethernet_read"></block>';
  html += '      <block type="ethernet_get_request"></block>';
  html += '      <!--block type="ethernet_post_request"></block-->';
  html += '    </category>';
  html += '  </category>';
  html += '  <sep></sep>';
  html += '  <category id="category_cloud_service">';
  html += '    <category id="category_ifttt">';
  html += '      <block type="text">';
  html += '        <field name="TEXT">maker.ifttt.com</field>';
  html += '      </block>';
  html += '      <block type="ifttt_get_url">';
  html += '        <value name="EVENT">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="KEY">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '    </category>';
  html += '    <category id="category_m2x">';
  html += '      <block type="m2x_begin">';
  html += '        <value name="ID">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="STREAM_NAME">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="KEY">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="m2x_update_value">';
  html += '        <value name="VALUE">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">1</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="m2x_list_value"></block>';
  html += '      <block type="m2x_custom_list_value"></block>';
  html += '      <block type="m2x_delete_values"></block>';
  html += '      <block type="m2x_update_location">';
  html += '        <value name="LOCATION_NAME">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '    </category>';
  html += '    <category id="category_blynk">';
  html += '      <block type="blynk_ethernet_begin">';
  html += '        <value name="AUTH">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="MAC_ADDRESS">';
  html += '          <block type="ethernet_mac_address"></block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="blynk_connect"></block>';
  html += '      <block type="blynk_write"></block>';
  html += '      <block type="blynk_param"></block>';
  html += '      <block type="blynk_merge_param"></block>';
  html += '      <block type="blynk_virtual_write">';
  html += '        <value name="VALUE">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">1</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="blynk_email">';
  html += '        <value name="ADDRESS">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="TITLE">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="BODY">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="blynk_notify">';
  html += '        <value name="TEXT">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="blynk_tweet">';
  html += '        <value name="TEXT">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '    </category>';
  html += '  </category>';
  html += '  <sep></sep>';
  html += '  <category name="Grove">';
  html += '    <category id="category_grove_input">';
  html += '      <block type="grove_button"></block>';
  html += '      <block type="grove_touch"></block>';
  html += '      <block type="grove_rotary_angle"></block>';
  html += '      <!--block type="grove_tilt_switch"></block-->';
  html += '      <!--block type="grove_thumb_joystick"></block-->';
  html += '    </category>';
  html += '    <category id="category_grove_output">';
  html += '      <block type="grove_led"></block>';
  html += '      <block type="grove_relay"></block>';
  html += '      <block type="grove_buzzer"></block>';
  html += '      <!--block type="grove_rgb_led"></block-->';
  html += '      <!--block type="grove_motor_shield"></block-->';
  html += '    </category>';
  html += '    <category id="category_grove_sensor">';
  html += '      <!--block type="grove_line_finder"></block-->';
  html += '      <!--block type="grove_pir_motion_sensor"></block-->';
  html += '      <block type="grove_light_sensor"></block>';
  html += '      <block type="grove_temporature_sensor"></block>';
  html += '      <block type="grove_sound_sensor"></block>';
  html += '      <!--block type="grove_ultrasonic_ranger"></block-->';
  html += '    </category>';
  html += '    <category id="category_lcd_rgb">';
  html += '      <block type="grove_rgb_lcd_begin"></block>';
  html += '      <block type="grove_rgb_lcd_print">';
  html += '        <value name="PRINT">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="grove_rgb_lcd_setcolor"></block>';
  html += '      <block type="grove_rgb_lcd_custom_setcursor">';
  html += '        <value name="COL">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="ROW">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="grove_rgb_lcd_clear"></block>';
  html += '      <!--block type="lcd_scrolldisplayright"></block-->';
  html += '      <!--block type="lcd_scrolldisplayleft"></block-->';
  html += '      <block type="grove_rgb_lcd_switch_scroll"></block>';
  html += '      <!--block type="lcd_lefttoright"></block-->';
  html += '      <!--block type="lcd_righttoleft"></block-->';
  html += '      <!--block type="grove_serial_lcd_power"></block-->';
  html += '      <!--block type="grove_serial_lcd_effect"></block-->';
  html += '    </category>';
  html += '  </category>';
  html += '  <category name="Adafruit">';
  html += '    <category id="category_rgbled">';
  html += '      <block type="rgbled_begin"></block>';
  html += '      <!--block type="rgbled_setpixelcolor"></block-->';
  html += '      <block type="rgbled_setpixelcolor2">';
  html += '        <value name="TARGET">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="rgbled_custom_setpixelcolor">';
  html += '        <value name="TARGET">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="R">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">255</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="G">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="B">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="rgbled_show"></block>';
  html += '    </category>';
  html += '    <category id="category_i2c_matrix">';
  html += '      <block type="i2c_matrix_begin"></block>';
  html += '      <block type="i2c_matrix_clear"></block>';
  html += '      <block type="i2c_matrix_writedisplay"></block>';
  html += '      <block type="i2c_matrix_setcursor">';
  html += '        <value name="COL">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="ROW">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="i2c_matrix_settextsize"></block>';
  html += '      <block type="i2c_matrix_settextwrap"></block>';
  html += '      <block type="i2c_matrix_settextcolor"></block>';
  html += '      <block type="i2c_matrix_print">';
  html += '        <value name="CONTENT">';
  html += '          <block type="text">';
  html += '            <field name="TEXT"></field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="i2c_matrix_setrotation"></block>';
  html += '      <block type="i2c_matrix_drawpixel">';
  html += '        <value name="X">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="Y">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="i2c_matrix_drawline">';
  html += '        <value name="X0">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="Y0">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="X1">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="Y1">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="i2c_matrix_drawcircle">';
  html += '        <value name="X">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="Y">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="D">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="i2c_matrix_drawrect">';
  html += '        <value name="X0">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="Y0">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="X1">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">5</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="Y1">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">5</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="i2c_matrix_fillrect">';
  html += '        <value name="X0">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="Y0">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="X1">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">5</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="Y1">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">5</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '    </category>';
  html += '    <category id="category_i2c_sevenseg">';
  html += '      <block type="i2c_sevenseg_begin"></block>';
  html += '      <block type="i2c_sevenseg_writedisplay"></block>';
  html += '      <block type="i2c_sevenseg_print">';
  html += '        <value name="NUM">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">7777</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="i2c_sevenseg_writedigitnum">';
  html += '        <value name="POSITION">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">0</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="NUM">';
  html += '          <block type="math_number">';
  html += '            <field name="NUM">1</field>';
  html += '          </block>';
  html += '        </value>';
  html += '        <value name="DOTS">';
  html += '          <block type="i2c_sevenseg_boolean">';
  html += '            <field name="BOOL">TRUE</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="i2c_sevenseg_drawcolon">';
  html += '        <value name="DOTS">';
  html += '          <block type="i2c_sevenseg_boolean">';
  html += '            <field name="BOOL">TRUE</field>';
  html += '          </block>';
  html += '        </value>';
  html += '      </block>';
  html += '      <block type="i2c_sevenseg_boolean"></block>';
  html += '    </category>';
  html += '  </category>';
  html += '  <category id="category_servo">';
  html += '    <block type="servo_write">';
  html += '      <value name="ANGLE">';
  html += '        <block type="math_number">';
  html += '          <field name="NUM">0</field>';
  html += '        </block>';
  html += '      </value>';
  html += '    </block>';
  html += '    <block type="servo_writeus">';
  html += '      <value name="ANGLE_US">';
  html += '        <block type="math_number">';
  html += '          <field name="NUM">0</field>';
  html += '        </block>';
  html += '      </value>';
  html += '    </block>';
  html += '    <block type="servo_read"></block>';
  html += '    <block type="servo_attached"></block>';
  html += '    <block type="servo_attach"></block>';
  html += '    <block type="servo_custom_attach"></block>';
  html += '    <block type="servo_detach"></block>';
  html += '  </category>';
  html += '  <category id="category_ultrasonic">';
  html += '    <block type="ultrasonic_setting"></block>';
  html += '    <block type="ultrasonic_maxrange"></block>';
  html += '    <block type="ultrasonic_distance"></block>';
  html += '  </category>';
  html += '  <category id="category_lcd">';
  html += '    <block type="lcd_init"></block>';
  html += '    <block type="lcd_begin"></block>';
  html += '    <block type="lcd_print">';
  html += '      <value name="PRINT">';
  html += '        <block type="text">';
  html += '          <field name="TEXT"></field>';
  html += '        </block>';
  html += '      </value>';
  html += '    </block>';
  html += '    <!--block type="lcd_setcursor"></block-->';
  html += '    <block type="lcd_custom_setcursor">';
  html += '      <value name="COL">';
  html += '        <block type="math_number">';
  html += '          <field name="NUM">0</field>';
  html += '        </block>';
  html += '      </value>';
  html += '      <value name="ROW">';
  html += '        <block type="math_number">';
  html += '          <field name="NUM">0</field>';
  html += '        </block>';
  html += '      </value>';
  html += '    </block>';
  html += '    <block type="lcd_clear"></block>';
  html += '    <!--block type="lcd_scrolldisplayright"></block-->';
  html += '    <!--block type="lcd_scrolldisplayleft"></block-->';
  html += '    <block type="lcd_switch_scroll"></block>';
  html += '    <!--block type="lcd_autoscroll"></block>';
  html += '<block type="lcd_noautoscroll"></block-->';
  html += '    <!--block type="lcd_lefttoright"></block-->';
  html += '    <!--block type="lcd_righttoleft"></block-->';
  html += '  </category>';
  html += '  <category id="category_other_sensor">';
  html += '    <block type="dht_read"></block>';
  html += '  </category>';
  html += '  <sep></sep>';
  html += '  <category id="category_logic">';
  html += '    <block type="controls_if"></block>';
  html += '    <block type="logic_compare"></block>';
  html += '    <block type="logic_operation"></block>';
  html += '    <block type="logic_negate"></block>';
  html += '    <block type="logic_boolean"></block>';
  html += '  </category>';
  html += '  <category id="category_loops">';
  html += '    <block type="controls_repeat"></block>';
  html += '    <block type="controls_for">';
  html += '      <value name="FROM">';
  html += '        <block type="math_number">';
  html += '          <field name="NUM">1</field>';
  html += '        </block>';
  html += '      </value>';
  html += '      <value name="TO">';
  html += '        <block type="math_number">';
  html += '          <field name="NUM">10</field>';
  html += '        </block>';
  html += '      </value>';
  html += '    </block>';
  html += '    <block type="controls_whileUntil"></block>';
  html += '    <block type="controls_flow_statements"></block>';
  html += '  </category>';
  html += '  <category id="category_time">';
  html += '    <block type="millis"></block>';
  html += '    <block type="micros"></block>';
  html += '    <block type="delay"></block>';
  html += '    <block type="delayMicroseconds"></block>';
  html += '  </category>';
  html += '  <category id="category_array">';
  html += '    <block type="array_create_with"></block>';
  html += '    <block type="array_getIndex">';
  html += '      <value name="AT">';
  html += '        <block type="math_number">';
  html += '          <field name="NUM">1</field>';
  html += '        </block>';
  html += '      </value>';
  html += '    </block>';
  html += '  </category>';
  html += '  <category id="category_math">';
  html += '    <block type="math_number"></block>';
  html += '    <block type="math_arithmetic"></block>';
  html += '    <block type="math_single"></block>';
  html += '    <block type="math_constrain"></block>';
  html += '    <block type="math_pow"></block>';
  html += '    <block type="math_random_max_min"></block>';
  html += '    <block type="math_map"></block>';
  html += '    <block type="math_custom_map"></block>';
  html += '  </category>';
  html += '  <category id="category_text">';
  html += '    <block type="text"></block>';
  html += '    <block type="text_commentout"></block>';
  html += '    <block type="text_length"></block>';
  html += '    <block type="text_charAt">';
  html += '      <value name="INDEX">';
  html += '        <block type="math_number">';
  html += '          <field name="NUM">1</field>';
  html += '        </block>';
  html += '      </value>';
  html += '    </block>';
  html += '  </category>';
  html += '  <sep></sep>';
  html += '  <category id="category_variables" custom="VARIABLE"></category>';
  html += '  <category id="category_functions" custom="PROCEDURE"></category>';
  html += '  <sep></sep>';
  html += '  <!--category id="category_involt">';
  html += '<block type="involt_directmode"></block>';
  html += '<block type="involt_chromereceive"></block>';
  html += '<block type="involt_sendvalue"></block>';
  html += '<block type="involt_receivevalue"></block>';
  html += '</category-->';
  html += '</xml>';
  document.write(html);
})();
